/* tslint:disable */
/* eslint-disable */
/**
 * kameleo-local-api
 * You can use the following API endpoints to communicate with the local running Kameleo programmatically.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface AddProfileToFolderRequest
 */
export interface AddProfileToFolderRequest {
    /**
     * Unique identifier of the profile.
     * @type {string}
     * @memberof AddProfileToFolderRequest
     */
    profileId: string;
}

/**
 * Check if a given object implements the AddProfileToFolderRequest interface.
 */
export function instanceOfAddProfileToFolderRequest(value: object): value is AddProfileToFolderRequest {
    if (!("profileId" in value) || value["profileId"] === undefined) return false;
    return true;
}

export function AddProfileToFolderRequestFromJSON(json: any): AddProfileToFolderRequest {
    return AddProfileToFolderRequestFromJSONTyped(json, false);
}

export function AddProfileToFolderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddProfileToFolderRequest {
    if (json == null) {
        return json;
    }
    return {
        profileId: json["profileId"],
    };
}

export function AddProfileToFolderRequestToJSON(json: any): AddProfileToFolderRequest {
    return AddProfileToFolderRequestToJSONTyped(json, false);
}

export function AddProfileToFolderRequestToJSONTyped(value?: AddProfileToFolderRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        profileId: value["profileId"],
    };
}
