/* tslint:disable */
/* eslint-disable */
/**
 * kameleo-local-api
 * You can use the following API endpoints to communicate with the local running Kameleo programmatically.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Specifies how the audio will be spoofed. Possible values:
 * 'noise': Add some noise to the Audio generation
 * 'block': Completely block the Audio API
 * 'off': Turn off the spoofing, use the original settings
 * @export
 */
export const AudioSpoofingType = {
    Off: "off",
    Noise: "noise",
    Block: "block",
} as const;
export type AudioSpoofingType = (typeof AudioSpoofingType)[keyof typeof AudioSpoofingType];

export function instanceOfAudioSpoofingType(value: any): boolean {
    for (const key in AudioSpoofingType) {
        if (Object.prototype.hasOwnProperty.call(AudioSpoofingType, key)) {
            if (AudioSpoofingType[key as keyof typeof AudioSpoofingType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AudioSpoofingTypeFromJSON(json: any): AudioSpoofingType {
    return AudioSpoofingTypeFromJSONTyped(json, false);
}

export function AudioSpoofingTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): AudioSpoofingType {
    return json as AudioSpoofingType;
}

export function AudioSpoofingTypeToJSON(value?: AudioSpoofingType | null): any {
    return value as any;
}

export function AudioSpoofingTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): AudioSpoofingType {
    return value as AudioSpoofingType;
}
