/* tslint:disable */
/* eslint-disable */
/**
 * kameleo-local-api
 * You can use the following API endpoints to communicate with the local running Kameleo programmatically.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface Browser
 */
export interface Browser {
    /**
     * Product of the browser. Possible values are 'chrome', 'firefox', 'edge', 'safari'.
     * @type {string}
     * @memberof Browser
     */
    product: string | null;
    /**
     * Major version of the browser.
     * @type {number}
     * @memberof Browser
     */
    major: number;
    /**
     * Exact version of the browser.
     * @type {string}
     * @memberof Browser
     */
    version: string | null;
}

/**
 * Check if a given object implements the Browser interface.
 */
export function instanceOfBrowser(value: object): value is Browser {
    if (!("product" in value) || value["product"] === undefined) return false;
    if (!("major" in value) || value["major"] === undefined) return false;
    if (!("version" in value) || value["version"] === undefined) return false;
    return true;
}

export function BrowserFromJSON(json: any): Browser {
    return BrowserFromJSONTyped(json, false);
}

export function BrowserFromJSONTyped(json: any, ignoreDiscriminator: boolean): Browser {
    if (json == null) {
        return json;
    }
    return {
        product: json["product"],
        major: json["major"],
        version: json["version"],
    };
}

export function BrowserToJSON(json: any): Browser {
    return BrowserToJSONTyped(json, false);
}

export function BrowserToJSONTyped(value?: Browser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        product: value["product"],
        major: value["major"],
        version: value["version"],
    };
}
