/* tslint:disable */
/* eslint-disable */
/**
 * kameleo-local-api
 * You can use the following API endpoints to communicate with the local running Kameleo programmatically.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CreateFolderRequest
 */
export interface CreateFolderRequest {
    /**
     * Human readable name of the new folder.
     * @type {string}
     * @memberof CreateFolderRequest
     */
    name: string;
}

/**
 * Check if a given object implements the CreateFolderRequest interface.
 */
export function instanceOfCreateFolderRequest(value: object): value is CreateFolderRequest {
    if (!("name" in value) || value["name"] === undefined) return false;
    return true;
}

export function CreateFolderRequestFromJSON(json: any): CreateFolderRequest {
    return CreateFolderRequestFromJSONTyped(json, false);
}

export function CreateFolderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateFolderRequest {
    if (json == null) {
        return json;
    }
    return {
        name: json["name"],
    };
}

export function CreateFolderRequestToJSON(json: any): CreateFolderRequest {
    return CreateFolderRequestToJSONTyped(json, false);
}

export function CreateFolderRequestToJSONTyped(value?: CreateFolderRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        name: value["name"],
    };
}
