/* tslint:disable */
/* eslint-disable */
/**
 * kameleo-local-api
 * You can use the following API endpoints to communicate with the local running Kameleo programmatically.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { DeviceMemorySpoofingType } from "./DeviceMemorySpoofingType";
import {
    DeviceMemorySpoofingTypeFromJSON,
    DeviceMemorySpoofingTypeFromJSONTyped,
    DeviceMemorySpoofingTypeToJSON,
    DeviceMemorySpoofingTypeToJSONTyped,
} from "./DeviceMemorySpoofingType";

/**
 *
 * @export
 * @interface DeviceMemoryChoice
 */
export interface DeviceMemoryChoice {
    /**
     *
     * @type {DeviceMemorySpoofingType}
     * @memberof DeviceMemoryChoice
     */
    value: DeviceMemorySpoofingType;
    /**
     *
     * @type {number}
     * @memberof DeviceMemoryChoice
     */
    extra?: number | null;
}

/**
 * Check if a given object implements the DeviceMemoryChoice interface.
 */
export function instanceOfDeviceMemoryChoice(value: object): value is DeviceMemoryChoice {
    if (!("value" in value) || value["value"] === undefined) return false;
    return true;
}

export function DeviceMemoryChoiceFromJSON(json: any): DeviceMemoryChoice {
    return DeviceMemoryChoiceFromJSONTyped(json, false);
}

export function DeviceMemoryChoiceFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeviceMemoryChoice {
    if (json == null) {
        return json;
    }
    return {
        value: DeviceMemorySpoofingTypeFromJSON(json["value"]),
        extra: json["extra"] == null ? undefined : json["extra"],
    };
}

export function DeviceMemoryChoiceToJSON(json: any): DeviceMemoryChoice {
    return DeviceMemoryChoiceToJSONTyped(json, false);
}

export function DeviceMemoryChoiceToJSONTyped(value?: DeviceMemoryChoice | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        value: DeviceMemorySpoofingTypeToJSON(value["value"]),
        extra: value["extra"],
    };
}
