/* tslint:disable */
/* eslint-disable */
/**
 * kameleo-local-api
 * You can use the following API endpoints to communicate with the local running Kameleo programmatically.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Specifies how the deviceMemory will be spoofed. Possible values:
 * 'automatic': Automatically set the values based on the fingerprint.
 * 'manual': Manually set the value in the profile. Valid values: 0.25, 0.5, 1, 2, 4, 8.
 * 'off': Turn off the spoofing, use the original settings.
 * @export
 */
export const DeviceMemorySpoofingType = {
    Automatic: "automatic",
    Manual: "manual",
    Off: "off",
} as const;
export type DeviceMemorySpoofingType = (typeof DeviceMemorySpoofingType)[keyof typeof DeviceMemorySpoofingType];

export function instanceOfDeviceMemorySpoofingType(value: any): boolean {
    for (const key in DeviceMemorySpoofingType) {
        if (Object.prototype.hasOwnProperty.call(DeviceMemorySpoofingType, key)) {
            if (DeviceMemorySpoofingType[key as keyof typeof DeviceMemorySpoofingType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DeviceMemorySpoofingTypeFromJSON(json: any): DeviceMemorySpoofingType {
    return DeviceMemorySpoofingTypeFromJSONTyped(json, false);
}

export function DeviceMemorySpoofingTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeviceMemorySpoofingType {
    return json as DeviceMemorySpoofingType;
}

export function DeviceMemorySpoofingTypeToJSON(value?: DeviceMemorySpoofingType | null): any {
    return value as any;
}

export function DeviceMemorySpoofingTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): DeviceMemorySpoofingType {
    return value as DeviceMemorySpoofingType;
}
