/* tslint:disable */
/* eslint-disable */
/**
 * kameleo-local-api
 * You can use the following API endpoints to communicate with the local running Kameleo programmatically.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * Defines the target location for profile export.
 * @export
 * @interface ExportProfileRequest
 */
export interface ExportProfileRequest {
    /**
     * Specifies the file path for exporting the profile.
     * @type {string}
     * @memberof ExportProfileRequest
     */
    path: string;
}

/**
 * Check if a given object implements the ExportProfileRequest interface.
 */
export function instanceOfExportProfileRequest(value: object): value is ExportProfileRequest {
    if (!("path" in value) || value["path"] === undefined) return false;
    return true;
}

export function ExportProfileRequestFromJSON(json: any): ExportProfileRequest {
    return ExportProfileRequestFromJSONTyped(json, false);
}

export function ExportProfileRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExportProfileRequest {
    if (json == null) {
        return json;
    }
    return {
        path: json["path"],
    };
}

export function ExportProfileRequestToJSON(json: any): ExportProfileRequest {
    return ExportProfileRequestToJSONTyped(json, false);
}

export function ExportProfileRequestToJSONTyped(value?: ExportProfileRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        path: value["path"],
    };
}
