/* tslint:disable */
/* eslint-disable */
/**
 * kameleo-local-api
 * You can use the following API endpoints to communicate with the local running Kameleo programmatically.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { Os } from "./Os";
import { OsFromJSON, OsFromJSONTyped, OsToJSON, OsToJSONTyped } from "./Os";
import type { Device } from "./Device";
import { DeviceFromJSON, DeviceFromJSONTyped, DeviceToJSON, DeviceToJSONTyped } from "./Device";
import type { WebglMeta } from "./WebglMeta";
import { WebglMetaFromJSON, WebglMetaFromJSONTyped, WebglMetaToJSON, WebglMetaToJSONTyped } from "./WebglMeta";
import type { Browser } from "./Browser";
import { BrowserFromJSON, BrowserFromJSONTyped, BrowserToJSON, BrowserToJSONTyped } from "./Browser";

/**
 * Provides a full view of a fingerprint, which encapsulates real-world browser fingerprint configurations used to
 * instantiate virtual browser profiles.
 * @export
 * @interface Fingerprint
 */
export interface Fingerprint {
    /**
     * The version of the fingerprint. As time passes new fingerprint versions will be introduced. It is recommended to use the latest one.
     * @type {string}
     * @memberof Fingerprint
     */
    version: string | null;
    /**
     * The unique identifier of the fingerprint. You can use this as a reference to create a new profile from this fingerprint.
     * @type {string}
     * @memberof Fingerprint
     */
    id: string | null;
    /**
     * The user agent of the browser fingerprint.
     * @type {string}
     * @memberof Fingerprint
     */
    userAgent: string | null;
    /**
     * Information about the device of the fingerprint.
     * @type {Device}
     * @memberof Fingerprint
     */
    device: Device | null;
    /**
     * Information about the OS of the fingerprint.
     * @type {Os}
     * @memberof Fingerprint
     */
    os: Os | null;
    /**
     * Information about the browser of the fingerprint.
     * @type {Browser}
     * @memberof Fingerprint
     */
    browser: Browser | null;
    /**
     * The GPU details extracted from WebGL parameters.
     * @type {WebglMeta}
     * @memberof Fingerprint
     */
    webglMeta: WebglMeta | null;
    /**
     * The screen size of the device in pixels.
     * @type {string}
     * @memberof Fingerprint
     */
    resolution: string | null;
    /**
     * A list of font types included in the profile.
     * @type {Array<string>}
     * @memberof Fingerprint
     */
    fonts: Array<string> | null;
}

/**
 * Check if a given object implements the Fingerprint interface.
 */
export function instanceOfFingerprint(value: object): value is Fingerprint {
    if (!("version" in value) || value["version"] === undefined) return false;
    if (!("id" in value) || value["id"] === undefined) return false;
    if (!("userAgent" in value) || value["userAgent"] === undefined) return false;
    if (!("device" in value) || value["device"] === undefined) return false;
    if (!("os" in value) || value["os"] === undefined) return false;
    if (!("browser" in value) || value["browser"] === undefined) return false;
    if (!("webglMeta" in value) || value["webglMeta"] === undefined) return false;
    if (!("resolution" in value) || value["resolution"] === undefined) return false;
    if (!("fonts" in value) || value["fonts"] === undefined) return false;
    return true;
}

export function FingerprintFromJSON(json: any): Fingerprint {
    return FingerprintFromJSONTyped(json, false);
}

export function FingerprintFromJSONTyped(json: any, ignoreDiscriminator: boolean): Fingerprint {
    if (json == null) {
        return json;
    }
    return {
        version: json["version"],
        id: json["id"],
        userAgent: json["userAgent"],
        device: DeviceFromJSON(json["device"]),
        os: OsFromJSON(json["os"]),
        browser: BrowserFromJSON(json["browser"]),
        webglMeta: WebglMetaFromJSON(json["webglMeta"]),
        resolution: json["resolution"],
        fonts: json["fonts"] == null ? null : json["fonts"],
    };
}

export function FingerprintToJSON(json: any): Fingerprint {
    return FingerprintToJSONTyped(json, false);
}

export function FingerprintToJSONTyped(value?: Fingerprint | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        version: value["version"],
        id: value["id"],
        userAgent: value["userAgent"],
        device: DeviceToJSON(value["device"]),
        os: OsToJSON(value["os"]),
        browser: BrowserToJSON(value["browser"]),
        webglMeta: WebglMetaToJSON(value["webglMeta"]),
        resolution: value["resolution"],
        fonts: value["fonts"],
    };
}
