/* tslint:disable */
/* eslint-disable */
/**
 * kameleo-local-api
 * You can use the following API endpoints to communicate with the local running Kameleo programmatically.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface GroupRole
 */
export interface GroupRole {
    /**
     * Unique identifier of the role.
     * @type {string}
     * @memberof GroupRole
     */
    id: string;
    /**
     * Name of the role.
     * @type {string}
     * @memberof GroupRole
     */
    name: string | null;
    /**
     * Description of the role.
     * @type {string}
     * @memberof GroupRole
     */
    description: string | null;
}

/**
 * Check if a given object implements the GroupRole interface.
 */
export function instanceOfGroupRole(value: object): value is GroupRole {
    if (!("id" in value) || value["id"] === undefined) return false;
    if (!("name" in value) || value["name"] === undefined) return false;
    if (!("description" in value) || value["description"] === undefined) return false;
    return true;
}

export function GroupRoleFromJSON(json: any): GroupRole {
    return GroupRoleFromJSONTyped(json, false);
}

export function GroupRoleFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupRole {
    if (json == null) {
        return json;
    }
    return {
        id: json["id"],
        name: json["name"],
        description: json["description"],
    };
}

export function GroupRoleToJSON(json: any): GroupRole {
    return GroupRoleToJSONTyped(json, false);
}

export function GroupRoleToJSONTyped(value?: GroupRole | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        id: value["id"],
        name: value["name"],
        description: value["description"],
    };
}
