/* tslint:disable */
/* eslint-disable */
/**
 * kameleo-local-api
 * You can use the following API endpoints to communicate with the local running Kameleo programmatically.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Specifies how the hardwareConcurrency will be spoofed. Possible values:
 * 'automatic': Automatically set the values based on the fingerprint.
 * 'manual': Manually set the value in the profile. Valid values: 1, 2, 4, 8, 12, 16.
 * 'off': Turn off the spoofing, use the original settings.
 * @export
 */
export const HardwareConcurrencySpoofingType = {
    Automatic: "automatic",
    Manual: "manual",
    Off: "off",
} as const;
export type HardwareConcurrencySpoofingType = (typeof HardwareConcurrencySpoofingType)[keyof typeof HardwareConcurrencySpoofingType];

export function instanceOfHardwareConcurrencySpoofingType(value: any): boolean {
    for (const key in HardwareConcurrencySpoofingType) {
        if (Object.prototype.hasOwnProperty.call(HardwareConcurrencySpoofingType, key)) {
            if (HardwareConcurrencySpoofingType[key as keyof typeof HardwareConcurrencySpoofingType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function HardwareConcurrencySpoofingTypeFromJSON(json: any): HardwareConcurrencySpoofingType {
    return HardwareConcurrencySpoofingTypeFromJSONTyped(json, false);
}

export function HardwareConcurrencySpoofingTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): HardwareConcurrencySpoofingType {
    return json as HardwareConcurrencySpoofingType;
}

export function HardwareConcurrencySpoofingTypeToJSON(value?: HardwareConcurrencySpoofingType | null): any {
    return value as any;
}

export function HardwareConcurrencySpoofingTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): HardwareConcurrencySpoofingType {
    return value as HardwareConcurrencySpoofingType;
}
