/* tslint:disable */
/* eslint-disable */
/**
 * kameleo-local-api
 * You can use the following API endpoints to communicate with the local running Kameleo programmatically.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * Specifies the source location for profile import.
 * @export
 * @interface ImportProfileRequest
 */
export interface ImportProfileRequest {
    /**
     * The file path from which the profile will be imported.
     * @type {string}
     * @memberof ImportProfileRequest
     */
    path: string;
}

/**
 * Check if a given object implements the ImportProfileRequest interface.
 */
export function instanceOfImportProfileRequest(value: object): value is ImportProfileRequest {
    if (!("path" in value) || value["path"] === undefined) return false;
    return true;
}

export function ImportProfileRequestFromJSON(json: any): ImportProfileRequest {
    return ImportProfileRequestFromJSONTyped(json, false);
}

export function ImportProfileRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImportProfileRequest {
    if (json == null) {
        return json;
    }
    return {
        path: json["path"],
    };
}

export function ImportProfileRequestToJSON(json: any): ImportProfileRequest {
    return ImportProfileRequestToJSONTyped(json, false);
}

export function ImportProfileRequestToJSONTyped(value?: ImportProfileRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        path: value["path"],
    };
}
