/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import * as msRest from "@azure/ms-rest-js";


export const Device: msRest.CompositeMapper = {
  serializedName: "Device",
  type: {
    name: "Composite",
    className: "Device",
    modelProperties: {
      type: {
        required: true,
        serializedName: "type",
        type: {
          name: "String"
        }
      },
      name: {
        readOnly: true,
        serializedName: "name",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const Os: msRest.CompositeMapper = {
  serializedName: "Os",
  type: {
    name: "Composite",
    className: "Os",
    modelProperties: {
      family: {
        required: true,
        serializedName: "family",
        type: {
          name: "String"
        }
      },
      version: {
        required: true,
        serializedName: "version",
        type: {
          name: "String"
        }
      },
      platform: {
        required: true,
        serializedName: "platform",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const Browser: msRest.CompositeMapper = {
  serializedName: "Browser",
  type: {
    name: "Composite",
    className: "Browser",
    modelProperties: {
      product: {
        required: true,
        serializedName: "product",
        type: {
          name: "String"
        }
      },
      major: {
        required: true,
        serializedName: "major",
        type: {
          name: "Number"
        }
      },
      version: {
        required: true,
        serializedName: "version",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const BaseProfile: msRest.CompositeMapper = {
  serializedName: "BaseProfile",
  type: {
    name: "Composite",
    className: "BaseProfile",
    modelProperties: {
      version: {
        required: true,
        serializedName: "version",
        type: {
          name: "String"
        }
      },
      id: {
        required: true,
        serializedName: "id",
        type: {
          name: "String"
        }
      },
      device: {
        required: true,
        serializedName: "device",
        type: {
          name: "Composite",
          className: "Device"
        }
      },
      os: {
        required: true,
        serializedName: "os",
        type: {
          name: "Composite",
          className: "Os"
        }
      },
      browser: {
        required: true,
        serializedName: "browser",
        type: {
          name: "Composite",
          className: "Browser"
        }
      },
      language: {
        required: true,
        serializedName: "language",
        type: {
          name: "String"
        }
      },
      resolution: {
        required: true,
        serializedName: "resolution",
        type: {
          name: "String"
        }
      },
      fonts: {
        required: true,
        serializedName: "fonts",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "String"
            }
          }
        }
      },
      plugins: {
        required: true,
        serializedName: "plugins",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "String"
            }
          }
        }
      }
    }
  }
};

export const BaseProfilePreview: msRest.CompositeMapper = {
  serializedName: "BaseProfilePreview",
  type: {
    name: "Composite",
    className: "BaseProfilePreview",
    modelProperties: {
      id: {
        required: true,
        serializedName: "id",
        type: {
          name: "String"
        }
      },
      device: {
        required: true,
        serializedName: "device",
        type: {
          name: "Composite",
          className: "Device"
        }
      },
      os: {
        required: true,
        serializedName: "os",
        type: {
          name: "Composite",
          className: "Os"
        }
      },
      browser: {
        required: true,
        serializedName: "browser",
        type: {
          name: "Composite",
          className: "Browser"
        }
      },
      language: {
        required: true,
        serializedName: "language",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const BaseProfileSearchParameters: msRest.CompositeMapper = {
  serializedName: "BaseProfileSearchParameters",
  type: {
    name: "Composite",
    className: "BaseProfileSearchParameters",
    modelProperties: {
      deviceTypes: {
        required: true,
        serializedName: "deviceTypes",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "String"
            }
          }
        }
      },
      osFamilies: {
        required: true,
        serializedName: "osFamilies",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "String"
            }
          }
        }
      },
      browserProducts: {
        required: true,
        serializedName: "browserProducts",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "String"
            }
          }
        }
      },
      languages: {
        required: true,
        serializedName: "languages",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "String"
            }
          }
        }
      }
    }
  }
};

export const BrowserCookie: msRest.CompositeMapper = {
  serializedName: "BrowserCookie",
  type: {
    name: "Composite",
    className: "BrowserCookie",
    modelProperties: {
      domain: {
        required: true,
        serializedName: "domain",
        type: {
          name: "String"
        }
      },
      name: {
        required: true,
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      path: {
        required: true,
        serializedName: "path",
        type: {
          name: "String"
        }
      },
      value: {
        required: true,
        serializedName: "value",
        type: {
          name: "String"
        }
      },
      hostOnly: {
        required: true,
        serializedName: "hostOnly",
        type: {
          name: "Boolean"
        }
      },
      httpOnly: {
        required: true,
        serializedName: "httpOnly",
        type: {
          name: "Boolean"
        }
      },
      secure: {
        required: true,
        serializedName: "secure",
        type: {
          name: "Boolean"
        }
      },
      sameSite: {
        required: true,
        serializedName: "sameSite",
        type: {
          name: "String"
        }
      },
      expirationDate: {
        readOnly: true,
        serializedName: "expirationDate",
        type: {
          name: "Number"
        }
      },
      session: {
        readOnly: true,
        serializedName: "session",
        type: {
          name: "Boolean"
        }
      },
      storeId: {
        readOnly: true,
        serializedName: "storeId",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const CookieRequest: msRest.CompositeMapper = {
  serializedName: "CookieRequest",
  type: {
    name: "Composite",
    className: "CookieRequest",
    modelProperties: {
      domain: {
        required: true,
        serializedName: "domain",
        type: {
          name: "String"
        }
      },
      name: {
        required: true,
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      path: {
        required: true,
        serializedName: "path",
        type: {
          name: "String"
        }
      },
      value: {
        required: true,
        serializedName: "value",
        type: {
          name: "String"
        }
      },
      hostOnly: {
        serializedName: "hostOnly",
        type: {
          name: "Boolean"
        }
      },
      httpOnly: {
        serializedName: "httpOnly",
        type: {
          name: "Boolean"
        }
      },
      secure: {
        serializedName: "secure",
        type: {
          name: "Boolean"
        }
      },
      sameSite: {
        serializedName: "sameSite",
        type: {
          name: "String"
        }
      },
      expirationDate: {
        serializedName: "expirationDate",
        type: {
          name: "Number"
        }
      }
    }
  }
};

export const WebglSpoofingOptions: msRest.CompositeMapper = {
  serializedName: "WebglSpoofingOptions",
  type: {
    name: "Composite",
    className: "WebglSpoofingOptions",
    modelProperties: {
      vendor: {
        serializedName: "vendor",
        type: {
          name: "String"
        }
      },
      renderer: {
        serializedName: "renderer",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const WebglSpoofingTypeWebglSpoofingOptionsMultiLevelChoice: msRest.CompositeMapper = {
  serializedName: "WebglSpoofingTypeWebglSpoofingOptionsMultiLevelChoice",
  type: {
    name: "Composite",
    className: "WebglSpoofingTypeWebglSpoofingOptionsMultiLevelChoice",
    modelProperties: {
      value: {
        required: true,
        serializedName: "value",
        type: {
          name: "String"
        }
      },
      extra: {
        serializedName: "extra",
        type: {
          name: "Composite",
          className: "WebglSpoofingOptions"
        }
      }
    }
  }
};

export const TimezoneSpoofingTypeTimezoneMultiLevelChoice: msRest.CompositeMapper = {
  serializedName: "TimezoneSpoofingTypeTimezoneMultiLevelChoice",
  type: {
    name: "Composite",
    className: "TimezoneSpoofingTypeTimezoneMultiLevelChoice",
    modelProperties: {
      value: {
        required: true,
        serializedName: "value",
        type: {
          name: "String"
        }
      },
      extra: {
        serializedName: "extra",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const GeolocationSpoofingOptions: msRest.CompositeMapper = {
  serializedName: "GeolocationSpoofingOptions",
  type: {
    name: "Composite",
    className: "GeolocationSpoofingOptions",
    modelProperties: {
      latitude: {
        required: true,
        serializedName: "latitude",
        type: {
          name: "Number"
        }
      },
      longitude: {
        required: true,
        serializedName: "longitude",
        type: {
          name: "Number"
        }
      }
    }
  }
};

export const GeolocationSpoofingTypeGeolocationSpoofingOptionsMultiLevelChoice: msRest.CompositeMapper = {
  serializedName: "GeolocationSpoofingTypeGeolocationSpoofingOptionsMultiLevelChoice",
  type: {
    name: "Composite",
    className: "GeolocationSpoofingTypeGeolocationSpoofingOptionsMultiLevelChoice",
    modelProperties: {
      value: {
        required: true,
        serializedName: "value",
        type: {
          name: "String"
        }
      },
      extra: {
        serializedName: "extra",
        type: {
          name: "Composite",
          className: "GeolocationSpoofingOptions"
        }
      }
    }
  }
};

export const Server: msRest.CompositeMapper = {
  serializedName: "Server",
  type: {
    name: "Composite",
    className: "Server",
    modelProperties: {
      host: {
        required: true,
        serializedName: "host",
        type: {
          name: "String"
        }
      },
      port: {
        required: true,
        serializedName: "port",
        type: {
          name: "Number"
        }
      },
      id: {
        serializedName: "id",
        type: {
          name: "String"
        }
      },
      secret: {
        serializedName: "secret",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const ProxyConnectionTypeServerMultiLevelChoice: msRest.CompositeMapper = {
  serializedName: "ProxyConnectionTypeServerMultiLevelChoice",
  type: {
    name: "Composite",
    className: "ProxyConnectionTypeServerMultiLevelChoice",
    modelProperties: {
      value: {
        required: true,
        serializedName: "value",
        type: {
          name: "String"
        }
      },
      extra: {
        serializedName: "extra",
        type: {
          name: "Composite",
          className: "Server"
        }
      }
    }
  }
};

export const WebRtcSpoofingOptions: msRest.CompositeMapper = {
  serializedName: "WebRtcSpoofingOptions",
  type: {
    name: "Composite",
    className: "WebRtcSpoofingOptions",
    modelProperties: {
      privateIp: {
        required: true,
        serializedName: "privateIp",
        type: {
          name: "String"
        }
      },
      publicIp: {
        required: true,
        serializedName: "publicIp",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const WebRtcSpoofingTypeWebRtcSpoofingOptionsMultiLevelChoice: msRest.CompositeMapper = {
  serializedName: "WebRtcSpoofingTypeWebRtcSpoofingOptionsMultiLevelChoice",
  type: {
    name: "Composite",
    className: "WebRtcSpoofingTypeWebRtcSpoofingOptionsMultiLevelChoice",
    modelProperties: {
      value: {
        required: true,
        serializedName: "value",
        type: {
          name: "String"
        }
      },
      extra: {
        serializedName: "extra",
        type: {
          name: "Composite",
          className: "WebRtcSpoofingOptions"
        }
      }
    }
  }
};

export const FontSpoofingTypeFontIListMultiLevelChoice: msRest.CompositeMapper = {
  serializedName: "FontSpoofingTypeFontIListMultiLevelChoice",
  type: {
    name: "Composite",
    className: "FontSpoofingTypeFontIListMultiLevelChoice",
    modelProperties: {
      value: {
        required: true,
        serializedName: "value",
        type: {
          name: "String"
        }
      },
      extra: {
        serializedName: "extra",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "String"
            }
          }
        }
      }
    }
  }
};

export const PluginSpoofingTypePluginIListMultiLevelChoice: msRest.CompositeMapper = {
  serializedName: "PluginSpoofingTypePluginIListMultiLevelChoice",
  type: {
    name: "Composite",
    className: "PluginSpoofingTypePluginIListMultiLevelChoice",
    modelProperties: {
      value: {
        required: true,
        serializedName: "value",
        type: {
          name: "String"
        }
      },
      extra: {
        serializedName: "extra",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "String"
            }
          }
        }
      }
    }
  }
};

export const ScreenSpoofingTypeScreenSizeMultiLevelChoice: msRest.CompositeMapper = {
  serializedName: "ScreenSpoofingTypeScreenSizeMultiLevelChoice",
  type: {
    name: "Composite",
    className: "ScreenSpoofingTypeScreenSizeMultiLevelChoice",
    modelProperties: {
      value: {
        required: true,
        serializedName: "value",
        type: {
          name: "String"
        }
      },
      extra: {
        serializedName: "extra",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const CreateProfileRequest: msRest.CompositeMapper = {
  serializedName: "CreateProfileRequest",
  type: {
    name: "Composite",
    className: "CreateProfileRequest",
    modelProperties: {
      baseProfileId: {
        required: true,
        serializedName: "baseProfileId",
        type: {
          name: "String"
        }
      },
      canvas: {
        required: true,
        serializedName: "canvas",
        type: {
          name: "String"
        }
      },
      webgl: {
        required: true,
        serializedName: "webgl",
        type: {
          name: "Composite",
          className: "WebglSpoofingTypeWebglSpoofingOptionsMultiLevelChoice"
        }
      },
      timezone: {
        required: true,
        serializedName: "timezone",
        type: {
          name: "Composite",
          className: "TimezoneSpoofingTypeTimezoneMultiLevelChoice"
        }
      },
      geolocation: {
        required: true,
        serializedName: "geolocation",
        type: {
          name: "Composite",
          className: "GeolocationSpoofingTypeGeolocationSpoofingOptionsMultiLevelChoice"
        }
      },
      proxy: {
        required: true,
        serializedName: "proxy",
        type: {
          name: "Composite",
          className: "ProxyConnectionTypeServerMultiLevelChoice"
        }
      },
      webRtc: {
        required: true,
        serializedName: "webRtc",
        type: {
          name: "Composite",
          className: "WebRtcSpoofingTypeWebRtcSpoofingOptionsMultiLevelChoice"
        }
      },
      fonts: {
        required: true,
        serializedName: "fonts",
        type: {
          name: "Composite",
          className: "FontSpoofingTypeFontIListMultiLevelChoice"
        }
      },
      plugins: {
        required: true,
        serializedName: "plugins",
        type: {
          name: "Composite",
          className: "PluginSpoofingTypePluginIListMultiLevelChoice"
        }
      },
      screen: {
        required: true,
        serializedName: "screen",
        type: {
          name: "Composite",
          className: "ScreenSpoofingTypeScreenSizeMultiLevelChoice"
        }
      },
      startPage: {
        serializedName: "startPage",
        type: {
          name: "String"
        }
      },
      passwordManager: {
        serializedName: "passwordManager",
        type: {
          name: "String"
        }
      },
      extensions: {
        serializedName: "extensions",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "String"
            }
          }
        }
      },
      notes: {
        serializedName: "notes",
        type: {
          name: "String"
        }
      },
      launcher: {
        serializedName: "launcher",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const LoadProfileRequest: msRest.CompositeMapper = {
  serializedName: "LoadProfileRequest",
  type: {
    name: "Composite",
    className: "LoadProfileRequest",
    modelProperties: {
      path: {
        required: true,
        serializedName: "path",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const Preference: msRest.CompositeMapper = {
  serializedName: "Preference",
  type: {
    name: "Composite",
    className: "Preference",
    modelProperties: {
      key: {
        required: true,
        serializedName: "key",
        type: {
          name: "String"
        }
      },
      value: {
        required: true,
        serializedName: "value",
        type: {
          name: "Object"
        }
      }
    }
  }
};

export const ProblemResponse: msRest.CompositeMapper = {
  serializedName: "ProblemResponse",
  type: {
    name: "Composite",
    className: "ProblemResponse",
    modelProperties: {
      code: {
        readOnly: true,
        serializedName: "code",
        type: {
          name: "Number"
        }
      },
      error: {
        serializedName: "error",
        type: {
          name: "Dictionary",
          value: {
            type: {
              name: "Sequence",
              element: {
                type: {
                  name: "String"
                }
              }
            }
          }
        }
      }
    }
  }
};

export const StatusResponse: msRest.CompositeMapper = {
  serializedName: "StatusResponse",
  type: {
    name: "Composite",
    className: "StatusResponse",
    modelProperties: {
      persistenceState: {
        required: true,
        serializedName: "persistenceState",
        type: {
          name: "String"
        }
      },
      lifetimeState: {
        required: true,
        serializedName: "lifetimeState",
        type: {
          name: "String"
        }
      },
      externalSpoofingEnginePort: {
        serializedName: "externalSpoofingEnginePort",
        type: {
          name: "Number"
        }
      }
    }
  }
};

export const ProfilePreview: msRest.CompositeMapper = {
  serializedName: "ProfilePreview",
  type: {
    name: "Composite",
    className: "ProfilePreview",
    modelProperties: {
      id: {
        required: true,
        serializedName: "id",
        type: {
          name: "Uuid"
        }
      },
      lastKnownPath: {
        serializedName: "lastKnownPath",
        type: {
          name: "String"
        }
      },
      device: {
        required: true,
        serializedName: "device",
        type: {
          name: "Composite",
          className: "Device"
        }
      },
      os: {
        required: true,
        serializedName: "os",
        type: {
          name: "Composite",
          className: "Os"
        }
      },
      browser: {
        required: true,
        serializedName: "browser",
        type: {
          name: "Composite",
          className: "Browser"
        }
      },
      language: {
        required: true,
        serializedName: "language",
        type: {
          name: "String"
        }
      },
      launcher: {
        required: true,
        serializedName: "launcher",
        type: {
          name: "String"
        }
      },
      status: {
        required: true,
        serializedName: "status",
        type: {
          name: "Composite",
          className: "StatusResponse"
        }
      }
    }
  }
};

export const ProfileResponse: msRest.CompositeMapper = {
  serializedName: "ProfileResponse",
  type: {
    name: "Composite",
    className: "ProfileResponse",
    modelProperties: {
      id: {
        required: true,
        serializedName: "id",
        type: {
          name: "Uuid"
        }
      },
      lastKnownPath: {
        serializedName: "lastKnownPath",
        type: {
          name: "String"
        }
      },
      createdAt: {
        required: true,
        serializedName: "createdAt",
        type: {
          name: "DateTime"
        }
      },
      baseProfile: {
        required: true,
        serializedName: "baseProfile",
        type: {
          name: "Composite",
          className: "BaseProfile"
        }
      },
      canvas: {
        required: true,
        serializedName: "canvas",
        type: {
          name: "String"
        }
      },
      webgl: {
        required: true,
        serializedName: "webgl",
        type: {
          name: "Composite",
          className: "WebglSpoofingTypeWebglSpoofingOptionsMultiLevelChoice"
        }
      },
      timezone: {
        required: true,
        serializedName: "timezone",
        type: {
          name: "Composite",
          className: "TimezoneSpoofingTypeTimezoneMultiLevelChoice"
        }
      },
      geolocation: {
        required: true,
        serializedName: "geolocation",
        type: {
          name: "Composite",
          className: "GeolocationSpoofingTypeGeolocationSpoofingOptionsMultiLevelChoice"
        }
      },
      proxy: {
        required: true,
        serializedName: "proxy",
        type: {
          name: "Composite",
          className: "ProxyConnectionTypeServerMultiLevelChoice"
        }
      },
      webRtc: {
        required: true,
        serializedName: "webRtc",
        type: {
          name: "Composite",
          className: "WebRtcSpoofingTypeWebRtcSpoofingOptionsMultiLevelChoice"
        }
      },
      fonts: {
        required: true,
        serializedName: "fonts",
        type: {
          name: "Composite",
          className: "FontSpoofingTypeFontIListMultiLevelChoice"
        }
      },
      plugins: {
        required: true,
        serializedName: "plugins",
        type: {
          name: "Composite",
          className: "PluginSpoofingTypePluginIListMultiLevelChoice"
        }
      },
      screen: {
        required: true,
        serializedName: "screen",
        type: {
          name: "Composite",
          className: "ScreenSpoofingTypeScreenSizeMultiLevelChoice"
        }
      },
      startPage: {
        required: true,
        serializedName: "startPage",
        type: {
          name: "String"
        }
      },
      passwordManager: {
        required: true,
        serializedName: "passwordManager",
        type: {
          name: "String"
        }
      },
      extensions: {
        required: true,
        serializedName: "extensions",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "String"
            }
          }
        }
      },
      notes: {
        required: true,
        serializedName: "notes",
        type: {
          name: "String"
        }
      },
      launcher: {
        required: true,
        serializedName: "launcher",
        type: {
          name: "String"
        }
      },
      status: {
        required: true,
        serializedName: "status",
        type: {
          name: "Composite",
          className: "StatusResponse"
        }
      }
    }
  }
};

export const SaveProfileRequest: msRest.CompositeMapper = {
  serializedName: "SaveProfileRequest",
  type: {
    name: "Composite",
    className: "SaveProfileRequest",
    modelProperties: {
      path: {
        required: true,
        serializedName: "path",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const TestProxyRequest: msRest.CompositeMapper = {
  serializedName: "TestProxyRequest",
  type: {
    name: "Composite",
    className: "TestProxyRequest",
    modelProperties: {
      proxy: {
        required: true,
        serializedName: "proxy",
        type: {
          name: "Composite",
          className: "ProxyConnectionTypeServerMultiLevelChoice"
        }
      }
    }
  }
};

export const TestProxyResponse: msRest.CompositeMapper = {
  serializedName: "TestProxyResponse",
  type: {
    name: "Composite",
    className: "TestProxyResponse",
    modelProperties: {
      isValidProxy: {
        required: true,
        serializedName: "isValidProxy",
        type: {
          name: "Boolean"
        }
      },
      message: {
        required: true,
        serializedName: "message",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const UpdateProfileRequest: msRest.CompositeMapper = {
  serializedName: "UpdateProfileRequest",
  type: {
    name: "Composite",
    className: "UpdateProfileRequest",
    modelProperties: {
      canvas: {
        required: true,
        serializedName: "canvas",
        type: {
          name: "String"
        }
      },
      webgl: {
        required: true,
        serializedName: "webgl",
        type: {
          name: "Composite",
          className: "WebglSpoofingTypeWebglSpoofingOptionsMultiLevelChoice"
        }
      },
      timezone: {
        required: true,
        serializedName: "timezone",
        type: {
          name: "Composite",
          className: "TimezoneSpoofingTypeTimezoneMultiLevelChoice"
        }
      },
      geolocation: {
        required: true,
        serializedName: "geolocation",
        type: {
          name: "Composite",
          className: "GeolocationSpoofingTypeGeolocationSpoofingOptionsMultiLevelChoice"
        }
      },
      proxy: {
        required: true,
        serializedName: "proxy",
        type: {
          name: "Composite",
          className: "ProxyConnectionTypeServerMultiLevelChoice"
        }
      },
      webRtc: {
        required: true,
        serializedName: "webRtc",
        type: {
          name: "Composite",
          className: "WebRtcSpoofingTypeWebRtcSpoofingOptionsMultiLevelChoice"
        }
      },
      fonts: {
        required: true,
        serializedName: "fonts",
        type: {
          name: "Composite",
          className: "FontSpoofingTypeFontIListMultiLevelChoice"
        }
      },
      plugins: {
        required: true,
        serializedName: "plugins",
        type: {
          name: "Composite",
          className: "PluginSpoofingTypePluginIListMultiLevelChoice"
        }
      },
      screen: {
        required: true,
        serializedName: "screen",
        type: {
          name: "Composite",
          className: "ScreenSpoofingTypeScreenSizeMultiLevelChoice"
        }
      },
      startPage: {
        required: true,
        serializedName: "startPage",
        type: {
          name: "String"
        }
      },
      passwordManager: {
        required: true,
        serializedName: "passwordManager",
        type: {
          name: "String"
        }
      },
      extensions: {
        serializedName: "extensions",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "String"
            }
          }
        }
      },
      notes: {
        serializedName: "notes",
        type: {
          name: "String"
        }
      },
      launcher: {
        serializedName: "launcher",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const UserInfoResponse: msRest.CompositeMapper = {
  serializedName: "UserInfoResponse",
  type: {
    name: "Composite",
    className: "UserInfoResponse",
    modelProperties: {
      userId: {
        required: true,
        serializedName: "userId",
        type: {
          name: "Uuid"
        }
      },
      email: {
        required: true,
        serializedName: "email",
        type: {
          name: "String"
        }
      },
      subscriptionEnd: {
        required: true,
        serializedName: "subscriptionEnd",
        type: {
          name: "DateTime"
        }
      },
      capabilities: {
        required: true,
        serializedName: "capabilities",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "String"
            }
          }
        }
      },
      lastAppLogin: {
        serializedName: "lastAppLogin",
        type: {
          name: "DateTime"
        }
      }
    }
  }
};

export const WebDriverSettings: msRest.CompositeMapper = {
  serializedName: "WebDriverSettings",
  type: {
    name: "Composite",
    className: "WebDriverSettings",
    modelProperties: {
      argumentsProperty: {
        serializedName: "arguments",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "String"
            }
          }
        }
      },
      preferences: {
        serializedName: "preferences",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "Preference"
            }
          }
        }
      },
      additionalOptions: {
        serializedName: "additionalOptions",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "Preference"
            }
          }
        }
      }
    }
  }
};
