/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";

export const browserProduct: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "browserProduct"
  ],
  mapper: {
    serializedName: "browserProduct",
    type: {
      name: "String"
    }
  }
};
export const deviceType: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "deviceType"
  ],
  mapper: {
    serializedName: "deviceType",
    type: {
      name: "String"
    }
  }
};
export const guid: msRest.OperationURLParameter = {
  parameterPath: "guid",
  mapper: {
    required: true,
    serializedName: "guid",
    type: {
      name: "Uuid"
    }
  }
};
export const language: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "language"
  ],
  mapper: {
    serializedName: "language",
    type: {
      name: "String"
    }
  }
};
export const osFamily: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "osFamily"
  ],
  mapper: {
    serializedName: "osFamily",
    type: {
      name: "String"
    }
  }
};
