/* tslint:disable */
/* eslint-disable */
/**
 * kameleo-local-api
 * You can use the following API endpoints to communicate with the local running Kameleo programmatically.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ProblemResponse
 */
export interface ProblemResponse {
    /**
     *
     * @type {number}
     * @memberof ProblemResponse
     */
    code?: number | null;
    /**
     *
     * @type {{ [key: string]: Array<string> | null; }}
     * @memberof ProblemResponse
     */
    error?: { [key: string]: Array<string> | null } | null;
}

/**
 * Check if a given object implements the ProblemResponse interface.
 */
export function instanceOfProblemResponse(value: object): value is ProblemResponse {
    return true;
}

export function ProblemResponseFromJSON(json: any): ProblemResponse {
    return ProblemResponseFromJSONTyped(json, false);
}

export function ProblemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProblemResponse {
    if (json == null) {
        return json;
    }
    return {
        code: json["code"] == null ? undefined : json["code"],
        error: json["error"] == null ? undefined : json["error"],
    };
}

export function ProblemResponseToJSON(json: any): ProblemResponse {
    return ProblemResponseToJSONTyped(json, false);
}

export function ProblemResponseToJSONTyped(value?: ProblemResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        code: value["code"],
        error: value["error"],
    };
}
