/* tslint:disable */
/* eslint-disable */
/**
 * kameleo-local-api
 * You can use the following API endpoints to communicate with the local running Kameleo programmatically.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const ProfileStorageLocation = {
    Local: "local",
    Cloud: "cloud",
} as const;
export type ProfileStorageLocation = (typeof ProfileStorageLocation)[keyof typeof ProfileStorageLocation];

export function instanceOfProfileStorageLocation(value: any): boolean {
    for (const key in ProfileStorageLocation) {
        if (Object.prototype.hasOwnProperty.call(ProfileStorageLocation, key)) {
            if (ProfileStorageLocation[key as keyof typeof ProfileStorageLocation] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ProfileStorageLocationFromJSON(json: any): ProfileStorageLocation {
    return ProfileStorageLocationFromJSONTyped(json, false);
}

export function ProfileStorageLocationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfileStorageLocation {
    return json as ProfileStorageLocation;
}

export function ProfileStorageLocationToJSON(value?: ProfileStorageLocation | null): any {
    return value as any;
}

export function ProfileStorageLocationToJSONTyped(value: any, ignoreDiscriminator: boolean): ProfileStorageLocation {
    return value as ProfileStorageLocation;
}
