/* tslint:disable */
/* eslint-disable */
/**
 * kameleo-local-api
 * You can use the following API endpoints to communicate with the local running Kameleo programmatically.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ProfileMinutesQuota
 */
export interface ProfileMinutesQuota {
    /**
     *
     * @type {string}
     * @memberof ProfileMinutesQuota
     */
    currentUsage?: string;
    /**
     *
     * @type {string}
     * @memberof ProfileMinutesQuota
     */
    maximumLimit?: string | null;
    /**
     *
     * @type {Date}
     * @memberof ProfileMinutesQuota
     */
    nextResetAt?: Date;
}

/**
 * Check if a given object implements the ProfileMinutesQuota interface.
 */
export function instanceOfProfileMinutesQuota(value: object): value is ProfileMinutesQuota {
    return true;
}

export function ProfileMinutesQuotaFromJSON(json: any): ProfileMinutesQuota {
    return ProfileMinutesQuotaFromJSONTyped(json, false);
}

export function ProfileMinutesQuotaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfileMinutesQuota {
    if (json == null) {
        return json;
    }
    return {
        currentUsage: json["currentUsage"] == null ? undefined : json["currentUsage"],
        maximumLimit: json["maximumLimit"] == null ? undefined : json["maximumLimit"],
        nextResetAt: json["nextResetAt"] == null ? undefined : new Date(json["nextResetAt"]),
    };
}

export function ProfileMinutesQuotaToJSON(json: any): ProfileMinutesQuota {
    return ProfileMinutesQuotaToJSONTyped(json, false);
}

export function ProfileMinutesQuotaToJSONTyped(value?: ProfileMinutesQuota | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        currentUsage: value["currentUsage"],
        maximumLimit: value["maximumLimit"],
        nextResetAt: value["nextResetAt"] == null ? undefined : value["nextResetAt"].toISOString(),
    };
}
