/* tslint:disable */
/* eslint-disable */
/**
 * kameleo-local-api
 * You can use the following API endpoints to communicate with the local running Kameleo programmatically.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface QuotaStatistics
 */
export interface QuotaStatistics {
    /**
     * Indicates the current usage, always a non-negative value.
     * @type {number}
     * @memberof QuotaStatistics
     */
    readonly currentUsage: number;
    /**
     * Indicates the maximum permitted value, with -1 implying no limit.
     * @type {number}
     * @memberof QuotaStatistics
     */
    readonly maximumLimit: number;
}

/**
 * Check if a given object implements the QuotaStatistics interface.
 */
export function instanceOfQuotaStatistics(value: object): value is QuotaStatistics {
    if (!("currentUsage" in value) || value["currentUsage"] === undefined) return false;
    if (!("maximumLimit" in value) || value["maximumLimit"] === undefined) return false;
    return true;
}

export function QuotaStatisticsFromJSON(json: any): QuotaStatistics {
    return QuotaStatisticsFromJSONTyped(json, false);
}

export function QuotaStatisticsFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuotaStatistics {
    if (json == null) {
        return json;
    }
    return {
        currentUsage: json["currentUsage"],
        maximumLimit: json["maximumLimit"],
    };
}

export function QuotaStatisticsToJSON(json: any): QuotaStatistics {
    return QuotaStatisticsToJSONTyped(json, false);
}

export function QuotaStatisticsToJSONTyped(
    value?: Omit<QuotaStatistics, "currentUsage" | "maximumLimit"> | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {};
}
