/* tslint:disable */
/* eslint-disable */
/**
 * kameleo-local-api
 * You can use the following API endpoints to communicate with the local running Kameleo programmatically.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { QuotaStatistics } from "./QuotaStatistics";
import {
    QuotaStatisticsFromJSON,
    QuotaStatisticsFromJSONTyped,
    QuotaStatisticsToJSON,
    QuotaStatisticsToJSONTyped,
} from "./QuotaStatistics";

/**
 *
 * @export
 * @interface RunningProfilesStatistics
 */
export interface RunningProfilesStatistics {
    /**
     * Quota usage of the profiles that are running with an automation framework.
     * @type {QuotaStatistics}
     * @memberof RunningProfilesStatistics
     */
    automated?: QuotaStatistics | null;
    /**
     * Quota usage of the profiles that are running manually (were started from GUI or API).
     * @type {QuotaStatistics}
     * @memberof RunningProfilesStatistics
     */
    manual?: QuotaStatistics | null;
    /**
     * Quota usage of the profiles that are running either manually or with an automation framework.
     * @type {QuotaStatistics}
     * @memberof RunningProfilesStatistics
     */
    total?: QuotaStatistics | null;
}

/**
 * Check if a given object implements the RunningProfilesStatistics interface.
 */
export function instanceOfRunningProfilesStatistics(value: object): value is RunningProfilesStatistics {
    return true;
}

export function RunningProfilesStatisticsFromJSON(json: any): RunningProfilesStatistics {
    return RunningProfilesStatisticsFromJSONTyped(json, false);
}

export function RunningProfilesStatisticsFromJSONTyped(json: any, ignoreDiscriminator: boolean): RunningProfilesStatistics {
    if (json == null) {
        return json;
    }
    return {
        automated: json["automated"] == null ? undefined : QuotaStatisticsFromJSON(json["automated"]),
        manual: json["manual"] == null ? undefined : QuotaStatisticsFromJSON(json["manual"]),
        total: json["total"] == null ? undefined : QuotaStatisticsFromJSON(json["total"]),
    };
}

export function RunningProfilesStatisticsToJSON(json: any): RunningProfilesStatistics {
    return RunningProfilesStatisticsToJSONTyped(json, false);
}

export function RunningProfilesStatisticsToJSONTyped(value?: RunningProfilesStatistics | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        automated: QuotaStatisticsToJSON(value["automated"]),
        manual: QuotaStatisticsToJSON(value["manual"]),
        total: QuotaStatisticsToJSON(value["total"]),
    };
}
