/* tslint:disable */
/* eslint-disable */
/**
 * kameleo-local-api
 * You can use the following API endpoints to communicate with the local running Kameleo programmatically.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ShareAccessRequest
 */
export interface ShareAccessRequest {
    /**
     * Id of the selected role.
     * @type {string}
     * @memberof ShareAccessRequest
     */
    roleId: string;
    /**
     * Id of the selected user.
     * @type {string}
     * @memberof ShareAccessRequest
     */
    userId: string;
}

/**
 * Check if a given object implements the ShareAccessRequest interface.
 */
export function instanceOfShareAccessRequest(value: object): value is ShareAccessRequest {
    if (!("roleId" in value) || value["roleId"] === undefined) return false;
    if (!("userId" in value) || value["userId"] === undefined) return false;
    return true;
}

export function ShareAccessRequestFromJSON(json: any): ShareAccessRequest {
    return ShareAccessRequestFromJSONTyped(json, false);
}

export function ShareAccessRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShareAccessRequest {
    if (json == null) {
        return json;
    }
    return {
        roleId: json["roleId"],
        userId: json["userId"],
    };
}

export function ShareAccessRequestToJSON(json: any): ShareAccessRequest {
    return ShareAccessRequestToJSONTyped(json, false);
}

export function ShareAccessRequestToJSONTyped(value?: ShareAccessRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        roleId: value["roleId"],
        userId: value["userId"],
    };
}
