/* tslint:disable */
/* eslint-disable */
/**
 * kameleo-local-api
 * You can use the following API endpoints to communicate with the local running Kameleo programmatically.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface UpdateFolderRequest
 */
export interface UpdateFolderRequest {
    /**
     * Human readable name of the folder.
     * @type {string}
     * @memberof UpdateFolderRequest
     */
    name: string;
}

/**
 * Check if a given object implements the UpdateFolderRequest interface.
 */
export function instanceOfUpdateFolderRequest(value: object): value is UpdateFolderRequest {
    if (!("name" in value) || value["name"] === undefined) return false;
    return true;
}

export function UpdateFolderRequestFromJSON(json: any): UpdateFolderRequest {
    return UpdateFolderRequestFromJSONTyped(json, false);
}

export function UpdateFolderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateFolderRequest {
    if (json == null) {
        return json;
    }
    return {
        name: json["name"],
    };
}

export function UpdateFolderRequestToJSON(json: any): UpdateFolderRequest {
    return UpdateFolderRequestToJSONTyped(json, false);
}

export function UpdateFolderRequestToJSONTyped(value?: UpdateFolderRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        name: value["name"],
    };
}
