/* tslint:disable */
/* eslint-disable */
/**
 * kameleo-local-api
 * You can use the following API endpoints to communicate with the local running Kameleo programmatically.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * When the WebGL Meta spoofing is used, these settings can override the values in the fingerprint.
 * @export
 * @interface WebglMetaSpoofingOptions
 */
export interface WebglMetaSpoofingOptions {
    /**
     * Unmasked vendor
     * @type {string}
     * @memberof WebglMetaSpoofingOptions
     */
    vendor?: string | null;
    /**
     * Unmasked renderer
     * @type {string}
     * @memberof WebglMetaSpoofingOptions
     */
    renderer?: string | null;
}

/**
 * Check if a given object implements the WebglMetaSpoofingOptions interface.
 */
export function instanceOfWebglMetaSpoofingOptions(value: object): value is WebglMetaSpoofingOptions {
    return true;
}

export function WebglMetaSpoofingOptionsFromJSON(json: any): WebglMetaSpoofingOptions {
    return WebglMetaSpoofingOptionsFromJSONTyped(json, false);
}

export function WebglMetaSpoofingOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebglMetaSpoofingOptions {
    if (json == null) {
        return json;
    }
    return {
        vendor: json["vendor"] == null ? undefined : json["vendor"],
        renderer: json["renderer"] == null ? undefined : json["renderer"],
    };
}

export function WebglMetaSpoofingOptionsToJSON(json: any): WebglMetaSpoofingOptions {
    return WebglMetaSpoofingOptionsToJSONTyped(json, false);
}

export function WebglMetaSpoofingOptionsToJSONTyped(value?: WebglMetaSpoofingOptions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        vendor: value["vendor"],
        renderer: value["renderer"],
    };
}
