/* tslint:disable */
/* eslint-disable */
/**
 * kameleo-local-api
 * You can use the following API endpoints to communicate with the local running Kameleo programmatically.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * When the WebRTC spoofing is set to manual these extra settings will be used as well.
 * @export
 * @interface WebRtcSpoofingOptions
 */
export interface WebRtcSpoofingOptions {
    /**
     * The WebRTC public IP address of the machine.
     * @type {string}
     * @memberof WebRtcSpoofingOptions
     */
    publicIp: string | null;
}

/**
 * Check if a given object implements the WebRtcSpoofingOptions interface.
 */
export function instanceOfWebRtcSpoofingOptions(value: object): value is WebRtcSpoofingOptions {
    if (!("publicIp" in value) || value["publicIp"] === undefined) return false;
    return true;
}

export function WebRtcSpoofingOptionsFromJSON(json: any): WebRtcSpoofingOptions {
    return WebRtcSpoofingOptionsFromJSONTyped(json, false);
}

export function WebRtcSpoofingOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebRtcSpoofingOptions {
    if (json == null) {
        return json;
    }
    return {
        publicIp: json["publicIp"],
    };
}

export function WebRtcSpoofingOptionsToJSON(json: any): WebRtcSpoofingOptions {
    return WebRtcSpoofingOptionsToJSONTyped(json, false);
}

export function WebRtcSpoofingOptionsToJSONTyped(value?: WebRtcSpoofingOptions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        publicIp: value["publicIp"],
    };
}
